---
title: "課堂練習模板>"
author: "Ken"
date: "2020-10-28"
output: output_format
params:
  id: "410672033"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
#建立一個變數名稱為我的年紀，其值為20。另外建立一個變數名稱為my_age，其值以呼叫我的年紀變數取得。
我的年紀 <- 20

my_age <- 我的年紀
cat(my_age)
```
```{r}
myName <- "Mary"

length(myName) # 查看物件本身代表幾個值。

cat(length(myName))

```
```{r}
stringInteger <- c("1","2","-11")

class(stringInteger) # 無法進行數值運算

typeof(stringInteger)
```
```{r}
studentId <- c(410773002, 410773015)

class(studentId
      )
a <- as.character(studentId)

class(a)
```
```{r}
library(lubridate)
```

```{r}
#2020-03-18 13:52:40 年月日時間

Taipei <- ymd_hms ("2020-03-18 13:52:40",tz="Asia/Taipei")

ymd_hms(
c("2020-03-18 13:52:40","2020-03-11 03:12:40")
) #若是UTC時間則不用設定tz

print(Taipei)#給人看

cat(Taipei)#秒數儲存

cat(as.character(Taipei))
```
```{r}
#Mar.18, 2020, 05:52:40 月日年時間
pgTime <- mdy_hms("Mar.18, 2020, 05:52:40",
                  tz="Europe/Lisbon")
```

```{r}
# Method 2: pass as a character that fits ISO8601 date time description standard with tz onset specified
tpeTime_iso8601 <- format_ISO8601(Taipei, usetz=T)

tpeTime_iso8601

tpeTime <- ymd_hms(tpeTime_iso8601)

cat(tpeTime_iso8601)
cat(tpeTime)
```
```{r}
object1 <- c(2,5)
object2 <- ymd_hms(
  c("2015-03-22 12:28:42","2017-12-22 15:33:48"),
  tz="Asia/Taipei"
)
object3 <- list(2, FALSE, c("a","b","c"))
save(object1, object2, object3, file="threeObjects.Rda")

```

```{r}
#選取元素
#1.用位置選 [[.]]
vectorExample <- c("小明", "小英", "大雄")

names(vectorExample)
# 有多少位置可選：
length(vectorExample)

listExample <- list(student = "小明", 學期 = list(`108-1` = list(list(name = "個體經濟學", 
    teacher = "Alice", grade = 85)), `108-2` = list(list(name = "總體經濟學", 
    teacher = "Mark", grade = 78))))

str(listExample)
str(listExample,1)
# 有多少位置可選：
length(listExample)

listExample[[1]]
listExample[[2]]
```
```{r}
#用名稱取，list獨有的($)，一定要名字選
# 有多少名字可選：
# 有多少名字可選：
names(listExample)

listExample$student
listExample$學期  # 特殊命名依然要用反頓點呼叫
```

```{r}
#位置多選
vectorExample

vectorExample[c(1, 3)]

# 顯示到第一層
str(listExample, max.level = 1)

listExample[c(1, 2)]
```

```{r}
#名字選
# 顯示到第一層
str(listExample, max.level = 1)

listExample[c("學期")]
listExample[c("student", "學期")]
```

```{r}
#要不要向量
vectorExample
vectorExample[c(T, T, F)]  # 要，要，不要
```
```{r}
pickbynum <- c(1,3)

pickbynumber <- c("p1","p3")

c(F,T,T) -> logicalNUM
```

```{r}
#連鎖選取
numVector <- c(2, 3, 6, -1, 4, 2, 6)

select1 <- numVector[c(1, 4)]

select1

select2 <- select1[[1]]

select2

# 相當於
numVector[c(1, 4)][[1]] #左先右後
```
```{r}
majors <- c("經濟學系", "經濟學系", "社會學系", "社工系", "經濟學系")

studentsnames <- c("小英", "小美", "大雄", "阿華", "阿尼")

gender <- c("F", "F", "M", "F", "M")


#which()邏輯轉數字
```
```{r}
today <- list(list("台北市", c(highest_temp = 25), c(lowest_temp = 18)), list("新北市", 
    c(highest_temp = 24), c(lowest_temp = 15)))
tomorrow <- list(list("台北市", c(highest_temp = 25), c(lowest_temp = 18)), list("新北市", 
    c(highest_temp = 24), c(lowest_temp = 15)))

weather <- list(today, tomorrow)

print(weather)
```

```{r}
weather[[1]][[2]][[2]]  # 今天/新北市/highest_temp
weather[[2]][[2]][[2]]  # 明天/新北市/highest_temp
```


