---
title: "課程練習模板"
author: "Ken"
date: "2020-11-22"
output: output_format
params:
  id: "410672033"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
#向量加減
a <- c(2, 3, 5)
b <- c(4,-1, 3)

a+b
a-b
a*b
a/b
a%%b #a除b勝的餘數
a**b

```


```{r}
a <- sample(1:15,5,replace = T)
a%%2 #可判斷奇偶數
```


```{r}
#recycle(or Broadcast in python)
# 狀況一: 堆疊一定倍數剛好一樣長
c(2,3)/c(-2,-13,10,22)
c(2,3,2,3)/c(-2,-13,10,22)

# 狀況二: 倍數堆疊一定會超過，只好截斷
c(2,3)/c(-2,-13,10)
c(2,3,2)/c(-2,-13,10)
```


```{r}
#dataframe
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)

tr_example <- purrr::transpose(example)
str(tr_example)
```


```{r}
df_example <- as.data.frame(example) #變表格的感覺 轉向 

# 使用list的工具
df_example$name[c(1,4)]

# 使用data frame的延伸工具`[.row, .column]`
df_example[c(1,4), "name"]
```


```{r}

```

```{r}
```


```{r}
```


```{r}
```

