---
title: "課程練習模板"
author: "Ken"
date: "2020-12-01"
output: output_format
params:
  id: "410672033"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
library(stringr)
library(glue)
```

```{r}
thatsAlright <- 
  jsonlite::fromJSON(
    "https://www.dropbox.com/s/f3ox7rd5favr0o0/thatsAlright.json?dl=1" )

View(thatsAlright)
class(thatsAlright)
length(thatsAlright)
```
```{r}
# 字串向量長度
length(c("I will")) #幾個元素值
# 每個元素值有幾個字元(包含符號與空格)
str_length(c("I will"))

```
```{r}
str_length(thatsAlright)#每個元素有幾個字元
```
```{r}
line67 <- thatsAlright[c(6,7)]
line67
line67 <- c(line67,"And very soon")
a <-str_split(line67, ", ") #看到逗號會切開
class(a)
```

```{r}
pattern="you" 

# 'you'是否出現在第1,2,3,...最後一句
pick_you <- str_detect(thatsAlright, pattern="you")
pick_you
str_view_all(thatsAlright[pick_you],"you") #框出符合條件字的位置

```


```{r}
# 哪幾句有'you'出現
whichHas_you <- str_which(thatsAlright, pattern="you")
whichHas_you
str_view_all(thatsAlright[whichHas_you],"you")

whichHas_you_fromPick <- which(pick_you)#留下要不要向量位置
whichHas_you_fromPick
```


```{r}
# 只留下有出現'you'字眼的句子
onlyYou <- str_subset(thatsAlright, pattern="you") #子集合

length(thatsAlright)
length(onlyYou)

```
```{r}
# 每一句有幾個"you"
countEach_you <- str_count(thatsAlright,
                           pattern="you")
countEach_you
str_view_all(
  thatsAlright[1:10], pattern="you")

```


```{r}
patternWithBoundary="\\byou\\b"
#若只要you這個字可前後加\\b定義字的boundary
str_view_all(
  c("I am yours",
    "And you?",
    "Young and smart", 
    "It means that you and I are lucky"),
  pattern=patternWithBoundary
)
```


```{r}
Rmdfiles <- c("file1.Rmd", "file2.R", "file3.rmd", "file4.RMD", "myRmd.R")
SchoolIds <- c("410973029", "410988011", "410974023","410783025","710773022","410788021","410673124","410873051","49988001")

```


```{r}
Rmdfiles
regexPattern="[Rr][Mm][Dd]"
str_subset(
  Rmdfiles, pattern=regexPattern)

# ignore case 指不分大小寫，用regex改
str_subset(Rmdfiles,pattern = regex("rmd",ignore_case = T))
```
```{r}
SchoolIds
regexPattern="[4](108|109)(73|88)" #中括號定義字元，小括號代表phrase

str_subset(
  SchoolIds, pattern=regexPattern)

```
```{r}
sameIdentities <- c("臺北市", "台北市", "台北大學", "臺北大學", "基隆市")

str_detect(
  sameIdentities, pattern="[台臺]") #只有一個捲帶

str_view_all(
  sameIdentities, pattern="[台臺]")

```

```{r}
str_extract(
  sameIdentities, pattern="[台臺]北市") #把字找出來
```
```{r}
dragonPeople <-
  c(
    "住在台北市的臺北人也常被稱為天龍人")
str_extract(
  dragonPeople,
  pattern="[台臺]北[市人]"
)
# 當一個元素值內的文字規律可多次出現時用_all來一網打盡，否則只處理第一個出現的規律
str_extract_all(
  dragonPeople,
  pattern="[台臺]北[市人]"
)
```


```{r}
Rmdfiles # length=5
str_replace(
  Rmdfiles,
  pattern = rep("[Rr][Mm][Dd]",5),
  replacement = rep("Rmd",5)
)  #次數都要一樣
```


```{r}
Rmdfiles # length=5
str_replace(
  Rmdfiles,
  pattern = "[Rr][Mm][Dd]",
  replacement = "Rmd"
)

```


```{r}
str_replace_all(
  string,
  c(
    "pattern1"="replacement1",
    "pattern2"="replacement2",
    
  )
)
```


```{r}
emailContent <- '親愛的_name_朋友好，

  恭喜你，你的電子發票號碼_invoiceNumber_ 差點中獎。'
cat(emailContent)

emailContent
```
```{r}
replacementNamedVector <- c(
  "_name_" = "小新",
  "_invoiceNumber_" = "EF-89400133"
)
replacementNamedVector

synthesizedContent <- str_replace_all(
  emailContent,
  replacementNamedVector
)
cat(synthesizedContent)
```


```{r}
```

