---
title: "課程練習模板"
author: "Ken"
date: "2020-11-21"
output: output_format
params:
  id: "410672033"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
numVector <- c(2,3,6,-1,4,2,6)
select1 <- numVector[c(1,4)]; select1
select2 <- select1[[1]]; select2

# 相當於
numVector[c(1,4)][[1]] #後取前
```
```{r}
AA = c(Mary=176, John=188, Jenny= 165, Kate=170)
LL = list(
  Mary=list(176,"Taipei"),
  John=list(188,"New Taipei"),
  Jenny=list(165,"Taichung"),
  Kate=list(170,"Hualien")
)
#取一個元素建議用兩個中刮號
AA[[1]]
AA[1]
str(AA)
str(AA[[1]])
str((AA[1]))
LL[[1]]
LL[1]
str(LL)
LL$Mary
```

```{r}
#新增元素
a <- c(2, 5, 7)
a[[4]] <- 8 #直接命名
a[[4]]
print(a)
```
```{r}
blue1 <- list(item="番茄牛丼",quantity="1")
blue2 <- list(item="起司番茄牛丼",quantity="1")
orderone <- list(blue1,blue2)

order1 <-list(
restaurant = "すき家 Sukiya (新北三峽店)",

date = lubridate::mdy("Nov 10, 2020"), #雙冒號是有lubridate的快捷使用

order = orderone,
total = 328 )
```


```{r}
#取出不存在的值
order1[["order"]][[2]] <- blue2

order1 <-list(
restaurant = "すき家 Sukiya (新北三峽店)",

date = lubridate::mdy("Nov 10, 2020"), #雙冒號是有lubridate的快捷使用

order = list(blue1),
total = 328 )

order1[["order"]][[2]]
```


```{r}
#多筆新增
a <- c(2, 5, 7)
a[c(4,5)] <- c(5,6)
a[c(4,5)]

```
```{r}
#多筆新增
blue3 <- list(item="牛丼飯",quantity="1") 
blue4 <- list(item="豬排飯",quantity="1")
a <- order1$order[c(3,4)] <- list(blue3,blue4) #使用[]留意要保留母層結構
```


```{r}
#修改與替換
library(lubridate)
LL0 <- LL <- list(
  "Mary was born on", 
  ymd("1995-7-1"),
  "John was born on",
  ymd("1997-10-27")
  )
LL[[2]]
LL[[2]] <- ymd("1995-7-8")
LL[[2]]
print(LL)
LL <- LL0
LL[c(2,4)]
LL <- LL0
LL[c(2,4)]
LL[c(2,4)] <- 
  list(
    ymd("1995-7-8"),
    ymd("1997-10-17")  #要跟母層一樣
  )
print(LL[c(2,4)])
```


```{r}
View(order1)
B <- order1$order[[1]][[2]] <- 2
```

```{r}
allmyclassmate <- list("阿榮","阿偉","阿鴻")

allmyclassmate[c(4,5)] <- list("阿堡","阿德")

allmyclassmate[c(4,5)]

allmyclassmate[[4]] <- "小白"

allmyclassmate[c(4,5)]
```
```{r}
#刪除
a <- c("L", "K", "Z")
a <- a[c(1,3)]
print(a) #只取要的

a <- c("L", "K", "Z")
a[-c(1,3)] # 不選1，3 
a <- a[-c(1,3)] # 刪去1, 3 僅限numeric vector
```
```{r}
LL <- list('a', T, 183)
LL[c(1,3)] <- NULL 
print(LL) 
```
```{r}
#加減乘除
a <- c(2, 3, 5)
b <- c(4,-1, 3)

a+b
a-b
a*b
a/b
```


```{r}
#判斷奇偶數
sequenceNums <- c(11, 6, 8, 11, 12, 11, 3, 7, 10, 8)
print(sequenceNums) #f1可查函數功能

sequenceNums %% 2 # 餘數為1則是奇數，0則是偶數

```


```{r}
```


```{r}
```


```{r}
```

