---
title: "課堂練習模板"
author: "Ken"
date: "2020-12-16"
output: output_format
params:
  id: "410672033"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
 library(stringr)
fruit <- c("apple", "banana", "pear", "pinapple")
str_detect(fruit, "a")
str_detect(fruit, "^a")
str_detect(fruit, "a$")
str_detect(fruit, "b")
str_detect(fruit, "[aeiou]")

# Also vectorised over pattern
str_detect("aecfg", letters)

# Returns TRUE if the pattern do NOT match
str_detect(fruit, "^p", negate = TRUE)
```

```{r}
a <- c(Mary=178, Jack=165)
attr(a, "family") <- "Johnson"
attributes(a)

b <- c(Ben=170, David=172)
attr(b, "family") <- "Jenson"
attributes(b)

a_b <- c(a, b)
attributes(a_b)
```


```{r}
list_ab <- list(a, b)
list_ab
attributes(list_ab)
attributes(a)
attributes(b)
```


```{r}
unlist_ab <- unlist(list_ab)
unlist_ab
attributes(unlist_ab)
```


```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")

is.na(a)
```
```{r}
library(purrr)
```


```{r}
sukiyaMenu <- jsonlite::fromJSON("https://www.dropbox.com/s/iu9b1hnvbtss83q/sukiyaMenu.json?dl=1")

nonsetMenu3 <- sukiyaMenu[c("豪華雙饗丼", "牛丼類", "咖哩類" )]

```


```{r}
items <- list()
items$dish_name = vector("list", length=3)
```


```{r}
# 餐點名稱
dish_name = nonsetMenu3[[1]]$name
items$dish_name[[1]] <- unlist(dish_name)

dish_name = nonsetMenu3[[2]]$name
items$dish_name[[2]] <- unlist(dish_name)

dish_name = nonsetMenu3[[3]]$name
items$dish_name[[3]] <- unlist(dish_name)
```


```{r}
# 餐點名稱
{
  dish_name <- nonsetMenu3[[1]]$name
  items$dish_name[[1]] <- unlist(dish_name)
}
{
  dish_name <- nonsetMenu3[[2]]$name
  items$dish_name[[2]] <- unlist(dish_name)
}
{
  dish_name <- nonsetMenu3[[3]]$name
  items$dish_name[[3]] <- unlist(dish_name)
}
```


```{r}
library(purrr)

map(
  list(
    list("Mary", 5),
    list("John", 10)
  ),
  ~{
    paste0(.x[[1]], " is ",.x[[2]], " years old")
  }
)
```


```{r}
library(stringr)
library(glue)
```


```{r}
thatsAlright <- 
  jsonlite::fromJSON(
    "https://www.dropbox.com/s/f3ox7rd5favr0o0/thatsAlright.json?dl=1"
  )

View(thatsAlright)
```


```{r}
# 字串向量長度
length(c("I will"))
# 每個元素值有幾個字元(包含符號與空格)
str_length(c("I will"))
```
```{r}
line67 <- thatsAlright[c(6,7)]
line67
```


```{r}
# 'you'是否出現在第1,2,3,...最後一句
pick_you <- str_detect(thatsAlright, pattern="you")
str_view_all(thatsAlright[pick_you],"you")
```

```{r}
# 哪幾句有'you'出現
whichHas_you <- str_which(thatsAlright, pattern="you")
whichHas_you
str_view_all(thatsAlright[whichHas_you],"you")
```


```{r}
# 每一句有幾個"you"
countEach_you <- str_count(thatsAlright,
                           pattern="\\byou\\b")
countEach_you
str_view_all(
  thatsAlright[1:10], pattern="\\byou\\b")
```


```{r}
# 只留下有出現'you'字眼的句子
onlyYou <- str_subset(thatsAlright, pattern="\\byou\\b")

length(thatsAlright)
length(onlyYou)
```

```{r}
Rmdfiles <- c("file1.Rmd", "file2.R", "file3.rmd", "file4.RMD", "myRmd.R")
SchoolIds <- c("410973029", "410988011", "410974023","410783025","710773022","410788021","410673124","410873051","49988001")
```

```{r}
Rmdfiles
regexPattern="[Rr][Mm][Dd]"
str_subset(
  Rmdfiles, pattern=regexPattern)
```

```{r}
SchoolIds
regexPattern="[4](108|109)(73|88)"
str_subset(
  SchoolIds, pattern=regexPattern)
```

```{r}
emailContent <- '親愛的_name_朋友好，

  恭喜你，你的電子發票號碼_invoiceNumber_ 差點中獎。'
replacementNamedVector <- c(
  "_name_" = "小新",
  "_invoiceNumber_" = "EF-89400133"
)

str_replace_all(emailContent,replacementNamedVector)
```

```{r}
addresses <- c(
  '臺中市后里區公館里尾社路385號',
  '新竹市東區科學園路125號1樓',
  '新竹市北區竹光路99號',
  '金門縣金城鎮賢庵里山前33號',
  '臺中市南屯區工業區二十四路23號1樓')

```

```{r}
str_extract(
  addresses,
  "(?<=[縣市])[\u4E00-\u9FFF]+[區鎮]"
)
```

```{r}
str_extract(
  addresses,
  "(?<=[縣市])[^區]+[區鎮]"
)
```


```{r}

```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

