---
title: "課堂練習模板"
author: "Ken"
date: "2020-12-14"
output: output_format
params:
  id: "410672033"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
eg1 <- list( list(name="Ken",id="410672033"),list(name="Mary",id="410672001")
  )

eg1[[1]][[1]]

eg1[c(1,2)]

eg1[[3]] <- list(name="a",id="410672055")

eg1[[3]]

eg1[-1]

eg1
```

```{r}
AA = c(Mary=176, John=188, Jenny= 165, Kate=170)
LL = list(
  Mary=list(176,"Taipei"),
  John=list(188,"New Taipei"),
  Jenny=list(165,"Taichung"),
  Kate=list(170,"Hualien")
)

LL[[1]]
LL[1]
```


```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)
```


```{r}
tr_example <- purrr::transpose(example)
str(tr_example)

df_example <- as.data.frame(example)
```


```{r}
# 使用list的工具
df_example$name[c(1,4)]

# 使用data frame的延伸工具`[.row, .column]`
df_example[c(1,4), "name"]
```


```{r}
library(stringr)
```


```{r}
CDC_chatbox <- readr::read_csv("http://od.cdc.gov.tw/pr/CDC_chatbox.csv")

 str_detect(CDC_chatbox$Question,"肺炎")

 pick_pneumonia <- stringr::str_detect(CDC_chatbox$Question,"肺炎")
CDC_chatbox$Question[pick_pneumonia]

```


```{r}



```


```{r}
```

