---
title: "課堂練習模板"
author: "Ken"
date: "2020-11-24"
output: output_format
params:
  id: "410672033"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O") )
```


```{r}
str(example)
df_example <- as.data.frame(example)
example$name[c(T, F, T, F)] #要、不要向量
```
```{r}
str(example[c("name","height")])

pick_above170 <- example$height >= 170
example$height
c(175, 166, 170, 160) >= 170

example$name[pick_above170]
```


```{r}
example$birthday
class(example$birthday)
typeof(example$birthday)

print(example[c("name","birthday")])

pick_after98 <- example$birthday >= lubridate::ymd("1998-01-01") #比大小的時候兩邊要是相同的type
example$name[pick_after98]
```


```{r}
print(example[c("name","allowance")])

pick_allowanceOver1000 <- example$allowance >= "1001-2000"

example$name[pick_allowanceOver1000]

class(example$allowance)
levels(example$allowance)
as.numeric(example$allowance)
```
```{r}
example$allowance %in% c( "1001-2000" ,"2000+" ) # %in%=屬於

example$allowance <- ordered(example$allowance) #轉成可排序的factor ， order的排序要事先排好
 
example$allowance
```
```{r}
example$allowance <- factor(example$allowance,levels = c("0-1000", "1001-2000" ,"2000+"),order=T)

#ORDER=T指可排序

pick_allowanceOver1000 <-example$allowance >="1001-2000"
example$name[pick_allowanceOver1000]
```


```{r}
print(example[c("name","bloodType")])

pick_bloodB <- example$bloodType == "B" # =跟<-意思一樣

pick_bloodB
example$name[pick_bloodB]
```

```{r}
df_example$bloodType ="B"
df_example$bloodType #recycle
```
```{r}
sequenceNums <- c(11, 6, 8, 11, 12, 11, 3, 7, 10, 8)
sequenceNums%%2
pick_evens <- (sequenceNums %% 2) == 0
sequenceNums[pick_evens]
```
```{r}
print(example[c("name","residence")])

set_TaipeiMetro <- c("Taipei","New Taipei")
pick_fromTaipeiMetro <- example$residence %in% set_TaipeiMetro

example$name[pick_fromTaipeiMetro]
```
```{r}
pick_not_fromTaipeiMetro <- ! pick_fromTaipeiMetro # !會變反
# 或
pick_not_fromTaipeiMetro <- !(example$residence %in% set_TaipeiMetro) # (..) 裡面會先運算完才做外面!的處理

```


```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華") #NA指沒有資料

class(x2)
is.na(x2) 

0/0
is.nan() #找缺失的數值運算
```
```{r}
print(example[c("name","hobby")])

pick_loveFood <- stringr::str_detect(example$hobby,"美食")#stringr::str_detect偵測是否有某些元素
example$name[pick_loveFood]
library(stringr)
```


```{r}
str_detect(example$hobby,"美食")
!str_detect(example$hobby,"美食")
```
```{r}

```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

